### ISSUE TITLE
dont work in parallel for nested frame created in new version of dplyr & tidyr

### ISSUE THREAD

**Issue by edvardoss** [DavisVaughan/furrr#86] opened 2019-10-14 07:43 UTC
since latest version dplyr/tidyr deep trap appeared (tested on windows 7) : my current scripts became is drustically slower - i found what groups break parallel processing.

May be it's not bug but users need any cautions about it!
```
library(dplyr)
library(tidyr)
d <- mtcars %>% group_by(carb) %>% nest 
d # Groups:   carb [6]

# sample function for test 
# (trouble may be appeared with any function, not necesserialy dplyr-pipeline! it just primer)
fn <- function(df){
  df %>% group_by(gear) %>% sample_n(size = 1e+7,replace = T) %>% 
    top_n(n = 3,wt = desc(disp)) %>% ungroup() %>% pull(mpg) %>% mean}

system.time(fn(d$data[[1]])) # 12 sec

library(furrr)
plan(multiprocess)
# process in 1 thread (if you whatch task maneger) and you see multiple sequental progress bar!
system.time(d <- d %>% mutate(test01=future_map(.x = data,.f = fn,.progress = T))) # 46 sec
# clean groups after nest and testing
d <- d %>% ungroup # or create nested frame without groups in results: d <- mtcars %>% group_nest(carb)
# that's OK!'
system.time(d <- d %>% mutate(test02=future_map(.x = data,.f = fn,.progress = T))) # 27 sec
d
plan(sequential)
```

**Comment by DavisVaughan** [comment] 2019-10-14 11:34
This looks like a duplicate of this issue 

https://github.com/DavisVaughan/furrr/issues/85#issuecomment-538377582

**Comment by edvardoss** [comment] 2019-10-15 04:09
Yes, it is. Anyway, there are not seems to me that its bug but this issue so critical that   large amount of users may get this trap. 
May be useful to generate force error and printing information in console about grouped frame?

**Comment by DavisVaughan** [comment] 2019-10-28 13:50
I appreciate the report, but this isn't something that furrr will be able to warn against.

**Closed by DavisVaughan** 2019-10-28 13:50 UTC
