### ISSUE TITLE
future_walk work in parallel in script function, but not in R package function

### ISSUE THREAD

**Issue by jinyancool** [DavisVaughan/furrr#236] opened 2022-05-24 07:04 UTC
Dear developer,
When I wrote an R scirpt function with future_walk, it can work in parallel, but if I wrap this R function in R package, it works in sequential.

> future::availableCores()
system 
   160 
################## R script function, it works fine.
mutect2 <- function(config, interval_dir){
  intervals    <- dir_ls(interval_dir, glob = "*-scattered.interval_list")
  oplan <- plan(multisession, workers = 60)
  on.exit(plan(oplan), add = TRUE)
  future_walk(intervals, ~ mutect2_wes_one(config, .x))
}

run: mutect2(config, interval_dir) is fine.

################## R package mypkg function, and call this function outside R package, e.g, mypkg::mutect2. It does not work as expected.

> future::availableCores()
system 
   160 
mutect2 <- function(config, interval_dir){
  intervals    <- dir_ls(interval_dir, glob = "*-scattered.interval_list")
  oplan <- plan(multisession, workers = 60)
  on.exit(plan(oplan), add = TRUE)
  future_walk(intervals, ~ mutect2_wes_one(config, .x))
}

run: mypkg::mutect2(config, interval_dir) does not work as expected.

**Comment by jinyancool** [comment] 2022-05-24 07:21
> packageVersion("furrr")
[1] '0.3.0.9000'

**Comment by jinyancool** [comment] 2022-05-24 10:46
https://cran.r-project.org/web/packages/future/vignettes/future-7-for-package-developers.html

The document at the above URL does not help.

**Comment by jinyancool** [comment] 2022-05-25 01:15
It does not fail. Just does not work as expected. Calling with R scirpt function, it can use 60 workers in parallel. Calling with R package function mypkg::mutect2(config, interval_dir), it only uses two workers in sequential. I can repeat this problem stably. I have tried .env_globals = rlang::global_env() or .env_globals = parent.frame(). It does not help.

future_walk(intervals, ~ mutect2_wes_one(config, .x), .env_globals = rlang::global_env())

**Comment by jinyancool** [comment] 2022-05-25 01:19
I just think it is the function calling environment that caused this problem.

**Comment by DavisVaughan** [comment] 2022-05-25 13:48
So the problem is that it is running sequentially when called through the package, even though you set `plan(multisession)` in the package function? But if you don't put it in a package then it correctly runs in parallel?

That sounds strange to me.

It is unlikely to be a function environment issue if that is the case.

Can you point me to a repo on GitHub that has this package in it? Or can you create a repo on GitHub that demonstrates this problem for you? I am unlikely to be able to help you otherwise

**Comment by DavisVaughan** [comment] 2022-05-25 13:50
By the way, setting `plan()` inside a function is typically not best practice. `plan()` should really only be called at the user level. Users should control whether or not the function runs in parallel, and the default should be to run sequentially.

**Comment by jinyancool** [comment] 2022-05-25 14:55
It is right. The problem is that it is running sequentially when called through the package, even though I set plan(multisession) in the package function. But if I don't put it in a package then it correctly runs in parallel.
I will try to upload the package to github. It is better that you have gatk installed.

**Comment by jinyancool** [comment] 2022-05-25 14:56
If I put the plan() outside the R package, it still cannot runs in parallel.

**Comment by jinyancool** [comment] 2022-06-01 06:02
> 

Can we solve this issue now? Thanks.

**Comment by DavisVaughan** [comment] 2023-02-08 14:53
Closing due to inability to reproduce

**Closed by DavisVaughan** 2023-02-08 14:53 UTC
Labels: reprex
